version: '3.7'

services:
    webserver:
        build: ./webserver/
        ports:
        - "888:80"
        working_dir: /var/www/
        volumes:
        - .:/var/www/
        depends_on:
        - database
    database:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      environment:
        - PMA_HOST=database
      depends_on:
        - database
    mail:
      image: mailhog/mailhog
      ports: 
        - 1025:1025
        - 8025:8025
